config/routes.rb
Rails.application.routes.draw do
  resources :drivers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:age, :race)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :driver_age %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_field :race, id: :driver_race %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Age</th>
      <th>Race</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.age %></td>
        <td><%= driver.race %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Age:</strong>
  <%= @driver.age %>
</p>

<p>
  <strong>Race:</strong>
  <%= @driver.race %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fltsopp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>